### ISSUE TITLE
see original repository license

### ISSUE THREAD

**Issue by Sueqkjs** [b23r0/rust-raknet#1]
https://github.com/BetterMC/raknet-rs/blob/master/LICENSE.md

**Comment by b23r0** [comment]
i will remove any your code

**Comment by b23r0** [comment]
To ensure compliance with your license, I will make this repository private within 24 hours, and make sure to remove your code (write.rs and read.rs) before making it public. If you have any other questions, you can reply me within 24 hours, if there is no reply, I will acquiesce you to approve this way of handling.

**Comment by b23r0** [comment]
Due to the ample working time on weekends, I will delete the relevant code (reader.rs and writer.rs) of your project within 24 hours, I will close this issue after deletion, if you have any other license issues, Reply me here, or email me. thanks.
