### ISSUE TITLE
Support customizable protocol version

### ISSUE THREAD

**Issue by extremeheat** [b23r0/rust-raknet#8]
In order to be compatible with minecraft, the raknet protocol version has to be configurable. It changed in various minecraft versions (without changes to raknet level). In 1.19.30 the latest raknet version is 11.

https://github.com/PrismarineJS/bedrock-protocol/blob/f88c8d0bc4ed252ad24ec3f9ad25da603dbc4db3/src/rak.js#L34

**Comment by b23r0** [comment]
I'll support it next week

**Comment by b23r0** [comment]
There are already contributors compatible with raknet 11 and merged, I will update raknet-node tomorrow.
